### ISSUE TITLE
Title string from Native XML import not recognized by Crossref plugin

### ISSUE THREAD

**Issue by ej2432** [pkp/crossref-ojs#26]
Hello! I just imported an issue to our OJS instance using the Native XML plugin. However, automatic registration of DOIs with the Crossref plugin failed. Manual deposit through the plugin also failed. This is the error text: "Deposit contains title error(s): Title name value is missing from the title element"

I exported the Crossref XML for review, and the <title> tag is empty. This seems like it may be a bug, since the title is present in the imported XML, and also in OJS. 

It looks similar to this bug, but I'm uploading articles from the same journal:https://forum.pkp.sfu.ca/t/crossref-submission-fails-because-plugin-expects-parameter-1-to-be-string-array-given-ojs-3-3-0-7/71366/2

I'm using this PHP program to generate my OJS Native XML:
https://github.com/ualbertalib/ojsxml

If it's not a bug, how should I fix the issue? Sorry if this is the wrong place to ask. Thanks for your help

**Comment by asmecher** [comment]
@ej2432, could you post this question on our support forum at https://forum.pkp.sfu.ca? That's the best place to get help. Be sure to include the version of OJS you're using.

**Comment by ej2432** [comment]
@asmecher Will do! Thanks for the reply.
