### ISSUE TITLE
Possibly incorrect string concatenation for XML name

### ISSUE THREAD

**Issue by t-mayer** [pkp/crossref-ojs#30]
Dear pkp-Team,
we were trying to deposit a large number of articles (ca. 100). However, the deposit action was resulting in errors. According to the error logs, the error message said that the file name was getting too long. After debugging I've noticed that the filename part is basically being reused with every iteration of the for-loop:
```
$objectsFileNamePart = $objectsFileNamePart . '-' . $object->getId();
```
Compared to the datacite plugin (where the variable is named $**object**FileNamePart):

```
$objectFileNamePart = $objectsFileNamePart . '-' . $object->getId();
```

Not sure if this is only an issue with our installation or if I am missing something...

OJS Version: 3.3.0.3
crossref-Plugin version: 2.1.0.0

Best,
Tina

**Comment by bozana** [comment]
Thanks @t-mayer! Please see the PR (ojs stable-3_3_0) for the fix.
