### ISSUE TITLE
Display index page for Tools > Import/Export > Crossref XML Export Plugin

### ISSUE THREAD

**Issue by bozana** [pkp/crossref-ojs#32]
**Describe the Bug:**
When going to Tools > Import/Export > Crossref XML Export Plugin an exception is thrown. Instead display the index.tpl page with further information, where to find the new settings and export possibilities.

Using OJS 3.4

PRs:
- https://github.com/pkp/crossref-ojs/pull/33
- https://github.com/pkp/ojs/pull/3880 (only submodule update)

**Comment by jonasraoni** [comment]
Please, check if it's the same issue:
https://github.com/pkp/pkp-lib/issues/8838

**Comment by bozana** [comment]
Oh yes, it is... I will then also fix the DataCite and move everything (the PRs) over there -- I found it is also generally better/easier to follow issues there in pkp-lib...
Thanks!
